name: Deploy to Production
on:
  push:
    branches: 
      - master
jobs:
  job_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.178.43
        username: pi
        password: ${{ secrets.IPM_SECRET }}
        port: 22
        script: |
          cd /var/www/html/ipm
          git pull origin master
          git status
