name: Deploy to Production
on:
  push:
    branches: 
      - master
jobs:
  job_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SECRET }}
        username: ${{ secrets.USER_SECRET }}
        key: ${{ secrets.IPM_SECRET }}
        port: 22
        script: |
          cd /var/www/html/ipm
          git pull origin master
          git status
